name: Build and Push

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t 192.168.1.53:5000/test-app:latest .

      - name: Push image to registry
        run: docker push 192.168.1.53:5000/test-app:latest
